version: '3.8'

services:
  api:
    image: api
    ports: 
      - '7890:7890'
    depends_on:
      - db
    environment:  
      DATABASE_URL: "postgres://db/alchemy"
      POSTGRES_PASSWORD: 'password'
      REQUIRE_SSL: false

  db:
    image: postgres
    ports: 
      - '5433:5432'
    environment: 
      POSTGRES_PASSWORD: 'password'
